from typing import List, Dict, Any


class ForecastTradingRepository:
    """
    Repository adapter for the trading strategy.

    For now this expects the forecast payload already generated by your existing
    forecast service.

    Later, we can connect this directly to:
    - forecast_request
    - forecast_asset
    - forecast_points
    - forecast_backtest
    - diagnostics
    """

    def __init__(self, forecast_service):
        self.forecast_service = forecast_service

    def get_latest_forecasts_for_trading(
        self,
        tickers: List[str],
        hours: int = 24,
    ) -> List[Dict[str, Any]]:
        response = self.forecast_service.forecast(
            tickers=tickers,
            hours=hours,
        )

        if isinstance(response, dict):
            return response.get("assets", [])

        return response