from typing import Dict, List, Protocol
from app.schemas.trading_signal_schema import TradingSignalOut


class ITradingSignalRepository(Protocol):
    def create(self, data: Dict) -> TradingSignalOut: ...
    def create_many(self, items: List[Dict]) -> List[TradingSignalOut]: ...
    def find_pending(self, limit: int = 100) -> List[TradingSignalOut]: ...
    def find_by_id(self, signal_id: int) -> TradingSignalOut | None: ...
